#! /bin/sh

# Workspace monitors
bspc monitor HDMI-1 -d I II III IV V
bspc monitor HDMI-2 -d VI VII VIII IX X

# Other Stuff
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Autostart
sxhkd &
picom &
feh --bg-fill ~/Pictures/Wallpapers/ngvJK19.jpeg
$HOME/.config/polybar/launch.sh
